version: "3.3"
services:
  spacejoyweb-admin:
    build: .
    container_name: spacejoyweb-admin
    image: spacejoy/spacejoyweb-admin
    restart: always
    ports:
      - "3000:3000"
    environment:
      - LETSENCRYPT_EMAIL=hello@ndllabs.com
      - LETSENCRYPT_HOST=admin.spacejoy.com
      - VIRTUAL_HOST=admin.spacejoy.com
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    links:
      - spacejoyweb-admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./_devops/nginx:/etc/nginx/conf.d
      - ./_devops/ssl:/certs
