version: "3.3"
services:
  spacejoyweb-admin:
    build:
      dockerfile: Dockerfile.staging
      context: .
    container_name: spacejoyweb-admin
    image: spacejoy/spacejoyweb-admin
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    links:
      - spacejoyweb-admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./_devops/staging/nginx:/etc/nginx/conf.d
      - ./_devops/ssl:/certs
